site_name: Documentación de Métodos Numéricos para ODE
nav:
  - Introducción: index.md
  - Referencia de Funciones: reference.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ode]
          site_dir: docs  
